apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mailroom.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mailroom.labels" . | nindent 4 }}
type: Opaque
stringData:
  MAILROOM_JMAP_TOKEN: {{ .Values.secrets.jmap_token | quote }}
  MAILROOM_CARDDAV_USERNAME: {{ .Values.secrets.carddav_username | quote }}
  MAILROOM_CARDDAV_PASSWORD: {{ .Values.secrets.carddav_password | quote }}
